services:
  bitcoind:
    image: registry.gitlab.com/hashbeam/docker/bitcoind:30.0
    command: "-fallbackfee=0.0002"
    environment:
      MYUID: 1000
      MYGID: 1000
      RPCAUTH: "user:84c66d54d736d8b02aaa5b02e07e759b$$cc56c229b2a49ae2bfd5932cc8a6135d435bb9a7ac037ddd351d65936082c03d"
    ports:
      - 18443:18443
    volumes:
      - ./datacore:/srv/app/.bitcoin
  electrs:
    image: registry.gitlab.com/hashbeam/docker/electrs:0.10.10
    environment:
      MYUID: 1000
      MYGID: 1000
      BTCPASS: "password"
    volumes:
      - ./dataindex:/srv/app/db
    depends_on:
      - bitcoind
    ports:
      - 50001:50001
  proxy:
    image: ghcr.io/rgb-tools/rgb-proxy-server:0.3.0
    ports:
      - 3000:3000
  vss-postgres:
    image: postgres:16-alpine
    profiles: ['vss']
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  vss-server:
    build:
      context: ./docker/vss-server
      dockerfile: ./Dockerfile
    image: vss-server:sigs-auth
    profiles: ['vss']
    ports:
      - 8081:8080
    environment:
      VSS_BIND_ADDRESS: "0.0.0.0:8080"
      VSS_PSQL_USERNAME: postgres
      VSS_PSQL_PASSWORD: postgres
      VSS_PSQL_ADDRESS: "vss-postgres:5432"
      VSS_PSQL_DEFAULT_DB: postgres
      VSS_PSQL_VSS_DB: vss
    depends_on:
      vss-postgres:
        condition: service_healthy
