//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
    fn table_name(&self) -> &str {
        "config"
    }
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
    pub idx: i32,
    pub encrypted_mnemonic: String,
    pub indexer_url: Option<String>,
    pub bitcoin_network: Option<String>,
    pub wallet_fingerprint: Option<String>,
    pub wallet_account_xpub_vanilla: Option<String>,
    pub wallet_account_xpub_colored: Option<String>,
    pub wallet_master_fingerprint: Option<String>,
    pub created_at: i64,
    pub updated_at: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
    Idx,
    EncryptedMnemonic,
    IndexerUrl,
    BitcoinNetwork,
    WalletFingerprint,
    WalletAccountXpubVanilla,
    WalletAccountXpubColored,
    WalletMasterFingerprint,
    CreatedAt,
    UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
    Idx,
}

impl PrimaryKeyTrait for PrimaryKey {
    type ValueType = i32;
    fn auto_increment() -> bool {
        false
    }
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
    type EntityName = Entity;
    fn def(&self) -> ColumnDef {
        match self {
            Self::Idx => ColumnType::Integer.def(),
            Self::EncryptedMnemonic => ColumnType::String(StringLen::None).def(),
            Self::IndexerUrl => ColumnType::String(StringLen::None).def().null(),
            Self::BitcoinNetwork => ColumnType::String(StringLen::None).def().null(),
            Self::WalletFingerprint => ColumnType::String(StringLen::None).def().null(),
            Self::WalletAccountXpubVanilla => ColumnType::String(StringLen::None).def().null(),
            Self::WalletAccountXpubColored => ColumnType::String(StringLen::None).def().null(),
            Self::WalletMasterFingerprint => ColumnType::String(StringLen::None).def().null(),
            Self::CreatedAt => ColumnType::BigInteger.def(),
            Self::UpdatedAt => ColumnType::BigInteger.def(),
        }
    }
}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
