plugins {
    id 'com.android.library'
    id 'kotlin-android'
}

android {
    namespace 'org.rgblightningnode'
    compileSdk 34

    defaultConfig {
        minSdk 26
        targetSdk 34

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['../../target/uniffi/kotlin-android/jniLibs']
            kotlin.srcDirs = ['../../target/uniffi/kotlin-android']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'net.java.dev.jna:jna:5.14.0@aar'
    implementation 'androidx.annotation:annotation:1.7.0'
    androidTestImplementation 'androidx.test:runner:1.5.2'
    androidTestImplementation 'androidx.test:rules:1.5.0'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
}
