name: Build

on:
  push:
    branches: [ "master", "stage", "dev" ]
  pull_request:
    branches: [ "master", "stage", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ nightly, stable, 1.88.0 ]
        name: [ linux, windows, macos ]
        include:
          - name: linux
            os: warp-ubuntu-latest-x64-16x
          - name: windows
            os: warp-windows-latest-x64-16x
          - name: macos
            os: warp-macos-latest-arm64-6x
    steps:
      - uses: ilammy/setup-nasm@v1
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{matrix.toolchain}}
          rustflags: ""
      - name: Build
        run: cargo build --release --features "uniffi,vls,vss"
