name: Lint code

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          rustflags: ""
      - name: Lint
        run: cargo clippy --all-targets -- -D warnings
      - name: Lint (electrum only)
        run: cargo clippy --all-targets --no-default-features --features electrum,block-sync,transaction-sync -- -D warnings
      - name: Lint (esplora only)
        run: cargo clippy --all-targets --no-default-features --features esplora,block-sync,transaction-sync -- -D warnings
      - name: Lint (block-sync only)
        run: cargo clippy --all-targets --no-default-features --features block-sync,electrum,esplora -- -D warnings
      - name: Lint (transaction-sync only)
        run: cargo clippy --all-targets --no-default-features --features transaction-sync,electrum,esplora -- -D warnings
