name: Lint code

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        features:
          - block-sync,electrum
          - block-sync,esplora
          - block-sync,electrum,esplora
          - transaction-sync,electrum
          - transaction-sync,esplora
          - transaction-sync,electrum,esplora
          - block-sync,transaction-sync,electrum
          - block-sync,transaction-sync,esplora
          - block-sync,transaction-sync,electrum,esplora
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
          rustflags: ""
      - name: Lint (${{ matrix.features }})
        run: cargo clippy --all-targets --no-default-features --features ${{ matrix.features }} -- -D warnings
